# This file configures github.com/golangci/golangci-lint.

version: "2"

run:
  timeout: 20m
  tests: true

output:
  formats:
    text:
      colors: true

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
    - staticcheck
    - bidichk
    - durationcheck
    - whitespace

    # - errcheck # lot of false positives
    # - contextcheck
    # - errchkjson # lots of false positives
    # - errorlint # this check crashes
    # - exhaustive # silly check
    # - makezero # false positives
    # - nilerr # several intentional

  exclusions:
    rules:
      - text: 'SA1019: event.TypeMux is deprecated: use Feed'
        linters: [staticcheck]
      - text: 'SA1019: strings.Title is deprecated'
        linters: [staticcheck]
      - text: 'SA1019: strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.'
        linters: [staticcheck]
      - text: 'SA1029: should not use built-in type string as key for value'
        linters: [staticcheck]
    paths:
      - core/genesis_alloc.go

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/ethereum/go-ethereum
