// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/mev.proto

package mevpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BuilderRelay_SendBidBlock_FullMethodName = "/mev.v1.BuilderRelay/SendBidBlock"
)

// BuilderRelayClient is the client API for BuilderRelay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BuilderRelay carries BEP-675 BidBlock traffic from builders over gRPC.
// Only SendBidBlock is served here: it is the sole large-payload (blob),
// latency-critical method. All other mev APIs stay on JSON-RPC.
type BuilderRelayClient interface {
	SendBidBlock(ctx context.Context, in *BidBlockRequest, opts ...grpc.CallOption) (*BidBlockResponse, error)
}

type builderRelayClient struct {
	cc grpc.ClientConnInterface
}

func NewBuilderRelayClient(cc grpc.ClientConnInterface) BuilderRelayClient {
	return &builderRelayClient{cc}
}

func (c *builderRelayClient) SendBidBlock(ctx context.Context, in *BidBlockRequest, opts ...grpc.CallOption) (*BidBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidBlockResponse)
	err := c.cc.Invoke(ctx, BuilderRelay_SendBidBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuilderRelayServer is the server API for BuilderRelay service.
// All implementations must embed UnimplementedBuilderRelayServer
// for forward compatibility.
//
// BuilderRelay carries BEP-675 BidBlock traffic from builders over gRPC.
// Only SendBidBlock is served here: it is the sole large-payload (blob),
// latency-critical method. All other mev APIs stay on JSON-RPC.
type BuilderRelayServer interface {
	SendBidBlock(context.Context, *BidBlockRequest) (*BidBlockResponse, error)
	mustEmbedUnimplementedBuilderRelayServer()
}

// UnimplementedBuilderRelayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuilderRelayServer struct{}

func (UnimplementedBuilderRelayServer) SendBidBlock(context.Context, *BidBlockRequest) (*BidBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendBidBlock not implemented")
}
func (UnimplementedBuilderRelayServer) mustEmbedUnimplementedBuilderRelayServer() {}
func (UnimplementedBuilderRelayServer) testEmbeddedByValue()                      {}

// UnsafeBuilderRelayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuilderRelayServer will
// result in compilation errors.
type UnsafeBuilderRelayServer interface {
	mustEmbedUnimplementedBuilderRelayServer()
}

func RegisterBuilderRelayServer(s grpc.ServiceRegistrar, srv BuilderRelayServer) {
	// If the following call panics, it indicates UnimplementedBuilderRelayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuilderRelay_ServiceDesc, srv)
}

func _BuilderRelay_SendBidBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderRelayServer).SendBidBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuilderRelay_SendBidBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderRelayServer).SendBidBlock(ctx, req.(*BidBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuilderRelay_ServiceDesc is the grpc.ServiceDesc for BuilderRelay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuilderRelay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mev.v1.BuilderRelay",
	HandlerType: (*BuilderRelayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendBidBlock",
			Handler:    _BuilderRelay_SendBidBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mev.proto",
}
